development: &default
  adapter: postgresql
  hostname: localhost
  port: 5432
  pool: 5
  database: linvoicer_development
  username: root
  password: 
test:
  <<: *default
  database: linvoicer_test
  min_messages: warning
production:
  <<: *default
  database: linvoicer_production
  min_messages: warning
