development: &default
  adapter: postgresql
  hostname: localhost
  port: 5432
  pool: 5
  database: linvoicer_development
  username: kev
  password:
test:
  <<: *default
  database: linvoicer_test
  min_messages: warning
production:
  url: <%= ENV["DATABASE_URL"] %>